version: '2.0'

services:
  user:
    image: postgres:9.6.2-alpine
    ports:
      - '5443:5432'
    environment:
      POSTGRES_USER: user-db
      POSTGRES_PASSWORD: user-db
      POSTGRES_DB: user-db
